### ISSUE TITLE
It seems FastLock can crash on rare occasions

### ISSUE THREAD

**Issue by acacuce** [ivlevAstef/SwiftLazy#6]
See realization of [Alamofire](https://github.com/Alamofire/Alamofire/blob/f96b619bcb2383b43d898402283924b80e2c4bae/Source/Protected.swift#L87)

And [explanation](https://forums.swift.org/t/atomic-property-wrapper-for-standard-library/30468/16) on Swift forum

**Comment by ivlevAstef** [comment]
Thanks. Show discussion and Alamofire implementation.
I change code.

But I'm use current implementation FastLock on three projects with many users. And FastLock used very often. 
But there was never a crash... "0.1% - 1% crash rate"...  don't think. 0.0000001% maybe... maybe

**Comment by ivlevAstef** [comment]
fixed into 1.1.9 version. Also I'll fix it soon in DITranquillity
