### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by makleso6** [ivlevAstef/SwiftLazy#7]
sometimes I get a hang when there is a value being received from different threads
Apparently the problem is that the semaphore is blocked

![one](https://github.com/user-attachments/assets/f6536482-97b2-4c17-a051-8eacc4b0219b)
![two](https://github.com/user-attachments/assets/252ec9d7-1a19-45bd-a6d8-2410dab97779)

**Comment by ivlevAstef** [comment]
Oh... Yes. I fixed at this weekend. It's very old bug... And stupid bug 😅

**Comment by ivlevAstef** [comment]
Fix in version https://github.com/ivlevAstef/SwiftLazy/releases/tag/v1.3.0
Thanks.
